<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        @page { margin: 25px; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 9px; color: #111827; }
        h1 { font-size: 18px; margin: 0 0 6px; }
        .meta { color: #6b7280; font-size: 9px; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #eef2ff; color: #1f2937; font-size: 8px; text-transform: uppercase; padding: 7px 5px; border: 1px solid #d1d5db; text-align: left; }
        td { padding: 6px 5px; border: 1px solid #e5e7eb; vertical-align: top; word-break: break-word; }
        tr:nth-child(even) td { background: #f9fafb; }
        .footer { margin-top: 12px; color: #6b7280; font-size: 8px; }
    </style>
</head>
<body>
    <h1>{{ $title }}</h1>
    <div class="meta">Generated by Eventora Super Admin on {{ now()->format('d M Y h:i A') }}</div>

    <table>
        <thead>
            <tr>
                @foreach($headings as $heading)
                    <th>{{ $heading }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $row)
                <tr>
                    @foreach($row as $value)
                        <td>{{ $value ?? '' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($headings) }}">No records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Eventora - Super Admin Report</div>
</body>
</html>
